### ISSUE TITLE
Error while running the plugin

### ISSUE THREAD

**Issue by AakashSharma7269** [vimsence/vimsence#52]
any idea why i'm getting this ;-;

Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aakash/.vim/plugged/vimsence/python/vimsence.py", line 62, in <module>
    has_thumbnail.update(thumbnails.values())
AttributeError: 'list' object has no attribute 'update'

**Comment by anned20** [comment]
What is your environment like? What OS are you using? What version of (Neo)Vim?

**Comment by anned20** [comment]
I resolved the first issue, maybe it resolved the other one too. Please test with the latest version.

**Comment by Shinyzenith** [comment]
I am using the latest version on Ubuntu 20.04 lts. I'll try cloning the repo again👍

**Comment by Shinyzenith** [comment]
Alright small update, i uninstalled snap version of discord and installed it using the .deb package on their website, it still throws the same errors at me but it does say Rpc connected and neovim idling and works when i start typing

**Comment by riziry** [comment]
i got the similar issue here but it says like this:
```
Error detected while processing function DiscordUpdatePresence[1]..<
SNR>42_InitializeDiscord[4]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/riziry/.local/share/nvim/plugged/vimsence/python/vimse
nce.py", line 62, in <module>
    has_thumbnail = list(set(has_thumbnail + custom_icons.values()))

TypeError: can only concatenate list (not "dict_values") to list
rovider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vimsence' is not defined
```

but if i comment this line in my .vimrc, it works just fine but without the icon on discord
``
let g:vimsence_custom_icons = {'filetype': 'iconname'}  
``
how to fix this?

**Comment by sideshowbarker** [comment]
The patch in https://github.com/vimsence/vimsence/pull/70 seems to fix this.
